### ISSUE TITLE
Updates needed for traces-01

### ISSUE THREAD

**Issue by gselander** [lake-wg/edhoc#253]
I've started to work on the update of -traces, see c936328e.

What is missing is:

* Trace 2: SUITES_I = [6, 2] instead of 2.

* Trace 2: Add bytes for raw x.509 (in addition to the CBOR encoded, see c936328e)
     * In total two new entries: CRED_I (Raw Value) and CRED_R (Raw Value)
     
* Trace 2: Pretty print of all byte strings
   * the analogue of vectors.txt for p256
   * 16 bytes per row
    * space between bytes

* Marek's address

@stoprocent could you help out here?

There is also TODO on version and reference which we need to fix, but that's just an editorial.

**Comment by gselander** [comment]
@stoprocent Submission deadline Monday in 10 days :-)

**Comment by stoprocent** [comment]
@gselander I will work on this today in the afternoon.

**Comment by stoprocent** [comment]
Hi

There was an incompatibility in the generator function for identifiers. This has been fixed here: https://github.com/stoprocent/edhoc/commit/abc197ef7372930c3c0d40dc4d0042cca27c6487
and updated test vectors are here: https://github.com/lake-wg/edhoc/pull/255

**Comment by gselander** [comment]
Thanks, I'll take a look later today.

**Comment by gselander** [comment]
New test vector included in trace 2.

**Comment by gselander** [comment]
We are still missing update of label/remove of "Master" in trace 1, per #205.

@emanjon @stoprocent Could anyone of you help?

(Replace "OSCORE_Master_Secret/Salt" with "OSCORE_Secret/Salt" and re-generate test vector for EdDSA in vectors.txt)

**Comment by marco-tiloca-sics** [comment]
> We are still missing update of label/remove of "Master" in trace 1, per https://github.com/lake-wg/edhoc/pull/205.
> 
> @emanjon @stoprocent Could anyone of you help?
> 
> (Replace "OSCORE_Master_Secret/Salt" with "OSCORE_Secret/Salt" and re-generate test vector for EdDSA in vectors.txt)

For the first trace using EdDSA, with the new labels "OSCORE_Secret" and "OSCORE_Salt", I derive:

OSCORE Master Secret (Raw Value) (16 bytes)
9565355973280280d64a3ce8d7fa0a93

OSCORE Master Salt (Raw Value) (8 bytes)
37478eddb09e5d7a

OSCORE Master Secret after KeyUpdate (Raw Value) (16 bytes)
ad4870dc7aca505bf80868785bd40d1b

OSCORE Master Salt after KeyUpdate (Raw Value) (8 bytes)
7138715cb50303a2

Can anyone confirm?

**Comment by gselander** [comment]
These updates are now completed.
